### ISSUE TITLE
[BUG] New QRcodeID generated even if the QRCodeID already exists

### ISSUE THREAD

**Issue by Siddharth-Chhatbar** [CMPUT301W23T14/QRHunter-App#102]
**Describe the bug**
The db generates new Id sometimes even if there already exists an instance of the qrCode in the db

**To Reproduce**
Scan the qrCode without location and delete the qrCode and try to scan it again with enabling location

**Expected behavior**
It should just add the qrCode to existing document

**Additional context**
N/A

**Comment by MaxxonTan** [comment]
Couldn't replicate this, can you do a screen recording?

**Comment by Siddharth-Chhatbar** [comment]
N/A

**Comment by MaxxonTan** [comment]
Relevant forum discussion [here ](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=2241781)
