### ISSUE TITLE
[US 01.01.01] Scan QR Code and retrieving its contents

### ISSUE THREAD

**Issue by lkaijie** [CMPUT301W23T14/QRHunter-App#11]
**Describe the user story**
As a player, I want to add new QR codes to my account. Part of #21 

**Describe the required task**
<img width="164" alt="image" src="https://user-images.githubusercontent.com/59834451/219551293-0f61ff1b-61b9-4afd-947c-10d4f77782a9.png">
Implement this activity, and:
- [x] Implement Android's [Camera api](https://developer.android.com/training/camerax) to scan 
- [x] Implement a QR code library to retrieve QR Code data. 
- [x] Save data into Firestore (No need to generate visuals and naming)
- [x] No need to save QR Code image as per #19 

**Additional context**
Risk level: Small

**Comment by mrbubbleman** [comment]
looks good to me!
