### ISSUE TITLE
[US 09.01.01 ] Don't store big images online

### ISSUE THREAD

**Issue by vtrieu5** [CMPUT301W23T14/QRHunter-App#14]
**Describe the user story**
As an owner, I don’t want to store big images online.

**Describe the user story**
Images are stored in lower resolution to preserve space (640x480)

**Additional context**
Decrease quality if needed must be < 100KB
Risk : L

**Comment by MaxxonTan** [comment]
@vtrieu5 Is it in the requirements / forum to store it in 640x480 and < 100kb? I can't seem to find it

**Comment by vtrieu5** [comment]
> @vtrieu5 Is it in the requirements / forum to store it in 640x480 and < 100kb? I can't seem to find it

Kai mentioned it to me but I believe it is this post 
https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=2195013

**Comment by MaxxonTan** [comment]
perfect thanks
