### ISSUE TITLE
[US 01.06.01] Show total number of QR codes

### ISSUE THREAD

**Issue by lkaijie** [CMPUT301W23T14/QRHunter-App#18]
**Describe the user story**
As a player, I want to see the total number of QR codes that I have scanned.

**Describe the required tasks**
Display QR code counter in the same fragment as #12 

**Additional context**
Risk Level: Low

**Comment by MaxxonTan** [comment]
With the UI we have currently, it's a text so the this is going to be very quick to implement. 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/59834451/219566410-2b719a67-707c-4cb9-b2a6-f65fcdb8ee4f.png">

Going to combine this to #13
