### ISSUE TITLE
[US 07.02.01] High Score Ranking

### ISSUE THREAD

**Issue by vtrieu5** [CMPUT301W23T14/QRHunter-App#23]
**Describe the user story**
As a player, I want an estimate of my ranking for the highest scoring unique QR code.

**Describe the required tasks**
Display ranking for highest scoring unique QR code
Determine where this ranking is displayed

**Additional context**
Risk: S
Clarify wording of unique QR code

**Comment by MaxxonTan** [comment]
Going to close this duplicate since this is just showing the QR Code that has the highest score, which is satisfied in issue #16 .

[Relevant forum post](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=2197916#p5685050)
