### ISSUE TITLE
[US 04.02.01] Auto Login

### ISSUE THREAD

**Issue by lkaijie** [CMPUT301W23T14/QRHunter-App#30]
**Describe the user story**
As a player, I do not want to log into my application using a username and password as my device can identify me.

**Describe the required tasks**
Generate secret value.
Do not implement password or login.

**Additional context**
Risk: M

**Comment by MaxxonTan** [comment]
@lkaijie What did you mean by secret value? Do u mean the user id cause that's gonna be auto generated by Firestore

**Comment by MaxxonTan** [comment]
Gonna mark this as duplicate. Will combine with #29

**Comment by lkaijie** [comment]
It is from here, https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=2195509 . I assume it is a value generated that is unique for every device. I'll check with my prof tmr

**Comment by MaxxonTan** [comment]
Ok yea I think the auto generated id from firebase will work, thanks
