### ISSUE TITLE
Storing photo of location/object

### ISSUE THREAD

**Issue by MaxxonTan** [CMPUT301W23T14/QRHunter-App#40]
**Describe the feature**
<img width="271" alt="image" src="https://user-images.githubusercontent.com/59834451/219554804-99acb3d6-6777-46a3-9955-c893c1df6184.png">
Add option for user to add a photo of the location. Only let the user have 1 picture and compress image for #14 

**Additional context**
Tracked in #21

**Comment by MaxxonTan** [comment]
The bitmap of the image is there locally, just need to store it into Firebase Storage

**Comment by harryz6560** [comment]
my bad do we also store it separately? I thought the photo was stored in location object that is part of the QRCode

**Comment by MaxxonTan** [comment]
No all good the issue didn't require you to store it to firebase anyways. And yeah you're right but I think there's a limit on how big the string can be in fire store, not sure yet. Probably need to do more research

**Comment by harryz6560** [comment]
ahh I see, I'll change things up if it does not work
