### ISSUE TITLE
User Interface Mockups and Storyboard Sequences

### ISSUE THREAD

**Issue by MaxxonTan** [CMPUT301W23T14/QRHunter-App#9]
> Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered.

Link to [Figma](https://www.figma.com/file/pGlodIhCfXQ9eHwcs5VKBJ/CMPUT301-UI-Design?node-id=0%3A1&t=s6ByYgf2jKU7x31N-1)

### Tasks
- [ ] Create interface mockup
- [ ] Create storyboard sequences

**Comment by mrbubbleman** [comment]
general user stories to be edited/updated in the future: 

[UI design.pdf](https://github.com/CMPUT301W23T14/QRHunter-App/files/10695783/UI.design.pdf)
